EgyNews/Areas/Blogger/Controllers/ArticleController.cs
using EgyNews.Data;
using EgyNews.Models;
using EgyNews.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EgyNews.Areas.Blogger.Controllers
{
    [Area("Blogger")]
    [Authorize(Roles = "Blogger,Admin")]
    public class ArticleController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ArticleController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var categories = _unitOfWork.Articles.GetAll();
            return View(categories);
        }

        public IActionResult Upsert(int? id)
        {
            ViewBag.Categories = _unitOfWork.Categories.GetAll()
                .Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                })
                .ToList();

            if (id != null && id != 0)
            {
                return View(_unitOfWork.Articles.Get(u => u.Id == id));
            }
                
            return View(new Article());
        }

        [HttpPost]
        public IActionResult Upsert(Article article, IFormFile? imageFile)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (imageFile != null)
                {
                    string filename = Guid.NewGuid().ToString() + Path.GetExtension(imageFile.FileName);
                    string articlePaht = Path.Combine(wwwRootPath, @"images\article");

                    if (!string.IsNullOrEmpty(article.ImageUrl))
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, article.ImageUrl);

                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStream = new FileStream(Path.Combine(articlePaht, filename), FileMode.Create))
                    {
                        imageFile.CopyTo(fileStream);
                    }

                    article.ImageUrl = @"\images\article\" + filename;
                }
                else
                {
                    if (article.Id == 0)
                    {
                        ViewBag.Categories = _unitOfWork.Categories.GetAll()
                        .Select(c => new SelectListItem
                        {
                            Value = c.Id.ToString(),
                            Text = c.Name
                        })
                        .ToList();
                        TempData["Error"] = "Failed to create article without uploading image";
                        return View(article);
                    }
                }
                if (article.Id == 0)
                {
                    _unitOfWork.Articles.Add(article);
                }
                else
                {
                    _unitOfWork.Articles.Update(article);
                }
                _unitOfWork.SaveChanges();
                TempData["Success"] = article.Id == 0 ? "Article created successfully" : "Article updated successfully";
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categories = _unitOfWork.Categories.GetAll()
                .Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.Name
                })
                .ToList();
            TempData["Error"] = article.Id == 0 ? "Failed to create article" : "Failed to update article";
            return View(article);
        }


        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var article = _unitOfWork.Articles.GetById(id);
            if (article == null)
            {
                return NotFound();
            }
            return View(article);
        }
        [HttpPost]
        public IActionResult Delete(Article article)
        {
            _unitOfWork.Articles.Delete(article.Id);
            _unitOfWork.SaveChanges();
            TempData["Success"] = "Article deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

EgyNews/Controllers/CategoryController.cs
using EgyNews.Data;
using EgyNews.Models;
using Microsoft.AspNetCore.Mvc;

namespace EgyNews.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var categories = _db.Categories.ToList();
            return View(categories);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category newCategory)
        {
            _db.Categories.Add(newCategory);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var category = _db.Categories.Find(id);
            if(category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            _db.Categories.Update(category);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            var category = _db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        public IActionResult Delete(Category category)
        {
            _db.Categories.Remove(category);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

EgyNews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EgyNews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EgyNews.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Reader" asp-controller="Home" asp-action="Index">EgyNews</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Reader" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_ManagementPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - EgyNews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EgyNews/Views/Shared/_ManagementPartial.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (SignInManager.IsSignedIn(User))
{
    var user = await UserManager.GetUserAsync(User);
    if (user != null)
    {
        var roles = await UserManager.GetRolesAsync(user);
        if (roles.Contains("Admin") || roles.Contains("Blogger"))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Blogger" asp-controller="Category" asp-action="Index">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Blogger" asp-controller="Article" asp-action="Index">Articles</a>
            </li>
        }
        if (roles.Contains("Admin"))
        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Admin" asp-action="Users">Users</a>
            </li>
        }
    }
}

EgyNews/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}